Fix for console error
menof36go/ttt2-utility pull request #1
Opened 2020-08-14 14:05 UTC by mexikoedi

Fix for this error: 
[[TTT/2] Utility Plugin] lua/scripts/sh_addonutil.lua:22: bad argument #1 to 'pairs' (table expected, got nil)
1. pairs - [C]:-1
2. GetMapFiles - lua/scripts/sh_addonutil.lua:22
3. GetMapFiles - lua/scripts/sh_addonutil.lua:23
4. GetMapFiles - lua/scripts/sh_addonutil.lua:23
5. GetMapFiles - lua/scripts/sh_addonutil.lua:23
6. SetupAddons - lua/scripts/sh_addonutil.lua:81
7. unknown - lua/autorun/sh_utility_init.lua:9

2020-08-22 15:24 UTC, menof36go requested changes
Sorry for my late review, I am very busy with university.
Thanks for your interest in helping with this project, but I do have some issues with this pull request:
"if nil then" essentially is evaluated to "if false then" in lua, which means that the if block will never be evaluated, so putting "if nil then" around the code causing the issue is essentially like commenting out the code. Instead of doing that we can simply check whether or not folders is nil between line 22 and 23 and return from the function if thats the case (this is called a guard clause or guard statement)
An example of a guard statement in lua would be:
`
if folders == nil then
    return
end
`

2020-08-23 18:51 UTC, mexikoedi commented
Thanks for the info. Now i know more about guard statements. I edited it and tested it.

2020-08-25 15:43 UTC, merged

2021-02-07 18:55 UTC, AaronMcKenney commented
Hey menof36go, can this be released onto Steam? I'm seeing the error mentioned here with the new TTT2 update.

2021-10-08 20:22 UTC, mexikoedi commented
> Hey menof36go, can this be released onto Steam? I'm seeing the error mentioned here with the new TTT2 update.

Now it is fixed on Steam too.